version = 0.1
[default.deploy.parameters]
stack_name = "si-sam-api2"
resolve_s3 = true
s3_prefix = "si-sam-api2"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
